const cfg=window.KRESCENDO_CONFIG||{},db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey),form=document.querySelector('#authForm'),message=document.querySelector('#authMessage');let register=false;
db.auth.getSession().then(function(r){if(r.data.session)showCustomerPanel(r.data.session)});
document.querySelector('#toggleMode').onclick=function(){register=!register;document.querySelector('#authTitle').textContent=register?'Registro por invitación':'Iniciar sesión';document.querySelector('#authSubmit').textContent=register?'Crear mi cuenta':'Entrar';document.querySelector('#inviteLabel').hidden=!register;document.querySelector('#inviteCode').required=register;this.textContent=register?'Ya tengo cuenta':'¿Tienes una invitación? Crear cuenta';message.textContent=''};
document.querySelector('#forgotPassword').onclick=async function(){const email=document.querySelector('#email').value.trim();if(!email){message.textContent='Escribe primero tu correo en el campo de arriba.';document.querySelector('#email').focus();return}this.disabled=true;message.textContent='Enviando enlace…';const r=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/reset-password.html'});this.disabled=false;message.textContent=r.error?'No se pudo enviar: '+r.error.message:'Listo. Revisa tu correo y abre el enlace para crear una contraseña nueva.'};
form.addEventListener('submit',async function(e){e.preventDefault();message.textContent='Procesando…';const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,invite=document.querySelector('#inviteCode').value.trim().toUpperCase();const r=register?await db.auth.signUp({email:email,password:password,options:{data:{invite_code:invite}}}):await db.auth.signInWithPassword({email:email,password:password});if(r.error){message.textContent=register?'No se pudo crear la cuenta. Revisa que la clave sea válida y no haya sido utilizada.':r.error.message;return}if(register&&!r.data.session){message.textContent='Cuenta creada. Revisa tu correo para confirmarla.';return}location.href=(JSON.parse(localStorage.getItem('krescendo_cart')||'[]').length?'checkout.html':'index.html')});

const authCard=document.querySelector('#authCard'),customerPanel=document.querySelector('#customerPanel'),warehouseSummary=document.querySelector('#warehouseSummary'),warehouseItems=document.querySelector('#warehouseItems'),warehouseMessage=document.querySelector('#warehouseMessage');let activeWarehouse=null;
function showCustomerPanel(session){const email=session.user.email||'';authCard.hidden=true;customerPanel.hidden=false;document.querySelector('#customerEmail').textContent=email;document.querySelector('#customerAdminAccess').hidden=email.toLowerCase()!==(cfg.adminEmail||'').toLowerCase();loadWarehouse()}
document.querySelector('#customerSignOut').onclick=async function(){await db.auth.signOut();location.reload()};
function storageCharge(freeUntil){const end=new Date(freeUntil),now=new Date();if(now<=end)return 0;return Math.ceil((now-end)/(30*24*60*60*1000))*150}
function dateMX(value){return new Date(value).toLocaleDateString('es-MX',{day:'2-digit',month:'long',year:'numeric'})}
async function loadWarehouse(){warehouseMessage.textContent='';const c=await db.from('warehouse_cycles').select('*').eq('status','active').maybeSingle();if(c.error){warehouseSummary.innerHTML='<div class="warehouse-empty"><h2>Falta activar el Almacén</h2><p>La administración debe ejecutar el archivo warehouse-setup.sql en Supabase.</p></div>';warehouseItems.innerHTML='';return}activeWarehouse=c.data;if(!activeWarehouse){warehouseSummary.innerHTML='<div class="warehouse-empty"><h2>Tu almacén está vacío</h2><p>Cuando llegue uno de tus productos aparecerá aquí. Tu mes gratuito comenzará con el primer ingreso.</p></div>';warehouseItems.innerHTML='';document.querySelector('#warehouseCount').textContent='0 productos';document.querySelector('#warehouseActions').hidden=true;return}const i=await db.from('warehouse_items').select('*').eq('cycle_id',activeWarehouse.id).order('arrived_at',{ascending:false});const items=i.data||[],charge=storageCharge(activeWarehouse.free_until),days=Math.max(0,Math.ceil((new Date(activeWarehouse.free_until)-new Date())/86400000));warehouseSummary.innerHTML='<article><span>Ciclo iniciado</span><b>'+dateMX(activeWarehouse.started_at)+'</b></article><article><span>Resguardo gratuito hasta</span><b>'+dateMX(activeWarehouse.free_until)+'</b></article><article><span>'+(charge?'Resguardo acumulado':'Días gratuitos restantes')+'</span><b>'+(charge?'$'+charge.toLocaleString('es-MX')+' MXN':days+' días')+'</b></article><article><span>Estado</span><b>'+(activeWarehouse.choice==='shipping'?'Envío solicitado':activeWarehouse.choice==='storage'?'En resguardo':'Por decidir')+'</b></article>';warehouseItems.innerHTML=items.map(function(x){return '<article class="warehouse-item">'+(x.image_url?'<img src="'+escapeHtml(x.image_url)+'" alt="">':'<div class="warehouse-placeholder">♡</div>')+'<div><small>Llegó el '+dateMX(x.arrived_at)+'</small><h3>'+escapeHtml(x.product_name)+'</h3><p>Cantidad: '+x.quantity+(x.notes?' · '+escapeHtml(x.notes):'')+'</p></div></article>'}).join('')||'<div class="warehouse-empty">Aún no hay productos registrados.</div>';document.querySelector('#warehouseCount').textContent=items.length+' producto'+(items.length===1?'':'s');document.querySelector('#warehouseActions').hidden=!items.length}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
async function chooseWarehouse(choice){warehouseMessage.textContent='Guardando tu elección…';const r=await db.rpc('set_warehouse_choice',{requested_choice:choice});warehouseMessage.textContent=r.error?'No se pudo guardar: '+r.error.message:choice==='shipping'?'Solicitud de envío enviada. Krescendo se pondrá en contacto contigo.':'Tus productos seguirán resguardados.';if(!r.error)loadWarehouse()}
document.querySelector('#keepStored').onclick=function(){chooseWarehouse('storage')};document.querySelector('#requestShipping').onclick=function(){if(confirm('¿Quieres solicitar el envío de todos los productos de tu almacén?'))chooseWarehouse('shipping')};
