create extension if not exists pgcrypto;
create table if not exists public.categories (id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,created_at timestamptz not null default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(),name text not null,artist text not null,category text not null references public.categories(slug) on update cascade on delete restrict,price numeric(10,2) not null default 0 check(price>=0),stock integer not null default 0 check(stock>=0),status text not null default 'stock' check(status in('stock','preorder')),image_url text,color text default '#ffe4ee',preorder_close date,eta text,active boolean not null default true,created_at timestamptz not null default now());
alter table public.categories enable row level security;
alter table public.products enable row level security;
create policy "Public can read categories" on public.categories for select using(true);
create policy "Public can read active products" on public.products for select using(active=true or auth.role()='authenticated');
create policy "Admins manage categories" on public.categories for all to authenticated using(true) with check(true);
create policy "Admins manage products" on public.products for all to authenticated using(true) with check(true);
insert into public.categories(name,slug) values('Álbumes','album'),('KGOODS','goods'),('KPOSTER','poster') on conflict(slug) do nothing;
insert into public.products(name,artist,category,price,stock,status,color) values('IVE — REVIVE+ Album','IVE','album',649,8,'stock','#ffe4ee'),('BLACKPINK Official Lightstick','BLACKPINK','goods',1299,4,'stock','#e8ddff'),('SEVENTEEN — Happy Burstday','SEVENTEEN','album',729,12,'stock','#d9f2ff'),('aespa — Armageddon Poster Set','aespa','poster',349,6,'stock','#fff0bd');
insert into public.products(name,artist,category,price,stock,status,color,preorder_close,eta) values('JENNIE — The Ruby Experience','JENNIE','album',799,0,'preorder','#f5dbea','2026-09-28','Envío estimado: noviembre'),('ENHYPEN — Desire : Unleash','ENHYPEN','album',749,0,'preorder','#dcecff','2026-10-04','Envío estimado: diciembre');
