/* Almacén privado de clientes */
(function(){
  const nav=document.querySelector('aside nav'),main=document.querySelector('#dashboard main'),header=main.querySelector('header');
  const warehouseNav=document.createElement('button');warehouseNav.id='warehouseNav';warehouseNav.dataset.view='warehouse';warehouseNav.textContent='Almacén';nav.insertBefore(warehouseNav,document.querySelector('#heroNav'));
  const addButton=document.createElement('button');addButton.id='newWarehouseItem';addButton.className='hidden';addButton.textContent='+ Producto recibido';header.appendChild(addButton);
  const view=document.createElement('section');view.id='warehouseView';view.className='panel hidden';view.innerHTML='<div class="invite-help">Registra aquí los productos que ya llegaron. El mes gratuito inicia con el primer producto del ciclo y se reinicia después de cerrar un envío.</div><div id="warehouseAdminList" class="warehouse-admin-list"></div>';main.appendChild(view);
  document.body.insertAdjacentHTML('beforeend','<dialog id="warehouseDialog" class="warehouse-admin-dialog"><form id="warehouseForm"><button type="button" class="warehouse-close close">×</button><small>NUEVO INGRESO</small><h2>Producto recibido</h2><div class="form-grid"><label class="wide">Cliente<select id="warehouseClient" required></select></label><label class="wide">Producto<input id="warehouseProduct" required placeholder="Ej. IVE — REVIVE+ Album"></label><label>Cantidad<input id="warehouseQuantity" type="number" min="1" value="1" required></label><label>Fecha de llegada<input id="warehouseArrival" type="date" required></label><label class="wide">URL de imagen<input id="warehouseImage" type="url" placeholder="https://..."></label><label class="wide">Nota<input id="warehouseNotes" placeholder="Versión, color o detalle opcional"></label></div><footer><button type="button" class="warehouse-cancel cancel">Cancelar</button><button type="submit">Guardar ingreso</button></footer><p id="warehouseError" class="warehouse-admin-error"></p></form></dialog>');
  const list=document.querySelector('#warehouseAdminList'),dialog=document.querySelector('#warehouseDialog'),warehouseForm=document.querySelector('#warehouseForm');
  function hideWarehouse(){view.classList.add('hidden');addButton.classList.add('hidden')}
  document.querySelectorAll('aside nav button:not(#warehouseNav)').forEach(function(b){b.addEventListener('click',hideWarehouse)});
  function fee(date){const end=new Date(date),now=new Date();return now<=end?0:Math.ceil((now-end)/(30*86400000))*150}
  function mxDate(v){return new Date(v).toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'})}
  async function loadWarehouse(){const clients=await db.rpc('list_warehouse_clients');if(clients.error){list.innerHTML='<div class="invite-help">Ejecuta warehouse-setup.sql en Supabase para activar esta sección.</div>';return}const cycles=await db.from('warehouse_cycles').select('*,warehouse_items(*)').eq('status','active').order('started_at',{ascending:false});if(cycles.error){note(cycles.error.message);return}list.innerHTML=(cycles.data||[]).map(function(x){const charge=fee(x.free_until),items=x.warehouse_items||[];return '<article class="warehouse-client-card"><div class="warehouse-client-head"><div><h3>'+esc(x.customer_email)+'</h3><p>Ciclo desde '+mxDate(x.started_at)+'</p></div><button data-close-cycle="'+x.id+'">Marcar enviado y cerrar</button></div><div class="warehouse-client-meta"><span>Gratis hasta '+mxDate(x.free_until)+'</span><span>'+(charge?'Cargo actual: $'+charge.toLocaleString('es-MX'):'Sin cargo')+'</span><span>'+(x.choice==='shipping'?'ENVÍO SOLICITADO':x.choice==='storage'?'EN RESGUARDO':'POR DECIDIR')+'</span></div><div class="warehouse-admin-items">'+items.map(function(i){return '<div class="warehouse-admin-item"><span><b>'+esc(i.product_name)+'</b> · '+i.quantity+' pza.</span><span>'+mxDate(i.arrived_at)+'</span></div>'}).join('')+'</div></article>'}).join('')||'<div class="invite-help">No hay almacenes activos. Agrega un producto recibido para iniciar uno.</div>'}
  warehouseNav.onclick=async function(){document.querySelectorAll('aside nav button').forEach(function(x){x.classList.remove('active')});warehouseNav.classList.add('active');productsView.classList.add('hidden');categoriesView.classList.add('hidden');document.querySelectorAll('#reviewsView,#heroView,#invitesView').forEach(function(x){x.classList.add('hidden')});view.classList.remove('hidden');document.querySelectorAll('#newProduct,#newReview,#newInvite').forEach(function(x){x.classList.add('hidden')});addButton.classList.remove('hidden');viewTitle.textContent='Almacén';await loadWarehouse()};
  addButton.onclick=async function(){const r=await db.rpc('list_warehouse_clients');warehouseClient.innerHTML=(r.data||[]).map(function(x){return '<option value="'+esc(x.email)+'">'+esc(x.email)+'</option>'}).join('');warehouseForm.reset();warehouseQuantity.value=1;warehouseArrival.value=new Date().toISOString().slice(0,10);warehouseError.textContent=r.error?r.error.message:'';dialog.showModal()};
  dialog.querySelector('.warehouse-close').onclick=dialog.querySelector('.warehouse-cancel').onclick=function(){dialog.close()};
  warehouseForm.onsubmit=async function(e){e.preventDefault();warehouseError.textContent='Guardando…';const r=await db.rpc('add_warehouse_item',{client_email:warehouseClient.value,item_name:warehouseProduct.value.trim(),item_quantity:Number(warehouseQuantity.value),item_image:warehouseImage.value.trim()||null,item_notes:warehouseNotes.value.trim()||null,item_arrived_at:warehouseArrival.value});if(r.error){warehouseError.textContent=r.error.message;return}dialog.close();note('Producto agregado al almacén');loadWarehouse()};
  list.onclick=async function(e){const id=e.target.dataset.closeCycle;if(!id||!confirm('¿Confirmas que este almacén ya fue enviado? El próximo ingreso iniciará un nuevo mes gratuito.'))return;const r=await db.rpc('close_warehouse_cycle',{warehouse_cycle_id:id});if(r.error)note(r.error.message);else{note('Almacén cerrado');loadWarehouse()}};
})();
